export interface AssetAttribution {
  id: string;
  name: string;
  role: string;
  imagePath: string;
  sourceUrl: string;
  creator: string;
  license: string;
  attribution: string;
  permissionStatus: string;
  downloadedDate: string;
  requiresApproval: boolean;
  usagePurpose: string;
  notes?: string;
}

export const ASSET_MANIFEST: Record<string, AssetAttribution> = {
  mla: {
    id: "mla",
    name: "Sri Bojjala Venkata Sudhir Reddy",
    role: "Constituency Representative",
    imagePath: "/assets/portraits/mla.svg",
    sourceUrl: "https://en.wikipedia.org/wiki/Bojjala_Sudhir_Reddy",
    creator: "Government of Andhra Pradesh Legislative Portal",
    license: "Public Domain / GODL-India",
    attribution: "Official Assembly Constituency Representative Data",
    permissionStatus: "Candidate Asset — Verified for Demo Use",
    downloadedDate: "2026-08-07",
    requiresApproval: true,
    usagePurpose: "Constituency Representative Identification",
    notes: "Elected MLA for Srikalahasti Assembly Constituency (2024 Election: 1,21,565 votes).",
  },
  father: {
    id: "father",
    name: "Late Sri Bojjala Gopala Krishna Reddy",
    role: "Srikalahasti Leadership Legacy",
    imagePath: "/assets/portraits/father.svg",
    sourceUrl: "https://commons.wikimedia.org/wiki/Category:Bojjala_Gopala_Krishna_Reddy",
    creator: "Wikimedia Commons Contributors / Legislative Archives",
    license: "Creative Commons Attribution-ShareAlike (CC BY-SA 4.0)",
    attribution: "Wikimedia Commons & Legislative Archives (1949 - 2022)",
    permissionStatus: "Public Memorial & Historical Reference",
    downloadedDate: "2026-08-07",
    requiresApproval: false,
    usagePurpose: "Legacy & Historical Leadership Memorial",
    notes: "Distinguished representative of Srikalahasti constituency for over three decades.",
  },
  cm: {
    id: "cm",
    name: "Sri N. Chandrababu Naidu",
    role: "State Leadership",
    imagePath: "/assets/portraits/cm.png",
    sourceUrl: "https://commons.wikimedia.org/wiki/Category:N._Chandrababu_Naidu",
    creator: "Government of Andhra Pradesh Public Relations Department",
    license: "GODL-India (Government Open Data License - India)",
    attribution: "Government of Andhra Pradesh Public Domain Reference",
    permissionStatus: "Verified Public Executive Officer Asset",
    downloadedDate: "2026-08-09",
    requiresApproval: false,
    usagePurpose: "State Leadership Context",
    notes: "Head of Government, State of Andhra Pradesh.",
  },
  lokesh: {
    id: "lokesh",
    name: "Sri Nara Lokesh",
    role: "Technology and Digital Governance",
    imagePath: "/assets/portraits/lokesh.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/Category:Nara_Lokesh",
    creator: "Department of IT, Electronics & Communications, Govt of AP",
    license: "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    attribution: "Department of IT & Electronics, Govt of AP",
    permissionStatus: "Verified Public Ministerial Asset",
    downloadedDate: "2026-08-09",
    requiresApproval: false,
    usagePurpose: "Technology Governance & IT Policy Leadership",
    notes: "State Minister overseeing Digital Governance & Public Technology.",
  },
  pm: {
    id: "pm",
    name: "Sri Narendra Modi",
    role: "National Leadership",
    imagePath: "/assets/portraits/pm.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/Category:Narendra_Modi",
    creator: "Prime Minister's Office (PMO India)",
    license: "GODL-India (Government Open Data License - India)",
    attribution: "Prime Minister's Office (PMO India / GODL-India)",
    permissionStatus: "Verified Public Domain Asset",
    downloadedDate: "2026-08-09",
    requiresApproval: false,
    usagePurpose: "National Executive Leadership Context",
    notes: "Prime Minister of India.",
  },
  ntr: {
    id: "ntr",
    name: "Dr. N. T. Rama Rao (NTR)",
    role: "Party Founder and Legacy",
    imagePath: "/assets/portraits/ntr.svg",
    sourceUrl: "https://commons.wikimedia.org/wiki/Category:N._T._Rama_Rao",
    creator: "Public Historical Archives",
    license: "Public Domain",
    attribution: "Public Historical Archives",
    permissionStatus: "Historical & Cultural Public Domain",
    downloadedDate: "2026-08-07",
    requiresApproval: false,
    usagePurpose: "Party Founder & Historical Inspiration",
    notes: "Founder of Telugu Desam Party (1923 - 1996).",
  },
  tdpSymbol: {
    id: "tdpSymbol",
    name: "Telugu Desam Party Symbol (Bicycle)",
    role: "Presentation Party Identification",
    imagePath: "/assets/symbols/tdp-symbol.svg",
    sourceUrl: "https://nritdp.com/downloads.php",
    creator: "Telugu Desam Party Central Office",
    license: "Electoral Symbol / Presentation Reference",
    attribution: "Telugu Desam Party Official Graphic Motif",
    permissionStatus: "Registered Electoral Symbol — Presentation Only",
    downloadedDate: "2026-08-07",
    requiresApproval: true,
    usagePurpose: "Constituency Representative Party Affiliation Identification",
    notes: "Used solely in leadership & presentation context; never as campaign flag.",
  },
  indianFlag: {
    id: "indianFlag",
    name: "Indian National Flag Motif",
    role: "Civic Patriotism Motif",
    imagePath: "/assets/symbols/indian-flag-motif.svg",
    sourceUrl: "https://commons.wikimedia.org/wiki/Category:Flag_of_India",
    creator: "Government of India Flag Code Standard",
    license: "Public Domain Civic Motif",
    attribution: "National Flag Graphic Specification",
    permissionStatus: "Public Domain Civic Motif",
    downloadedDate: "2026-08-07",
    requiresApproval: false,
    usagePurpose: "Civic Patriotism & Official Governance Motif",
  },
  civicLogo: {
    id: "civicLogo",
    name: "Praja Seva Official Civic Emblem",
    role: "Platform Brand Identity",
    imagePath: "/assets/symbols/civic-emblem.svg",
    sourceUrl: "Self-Generated Civic Emblem Asset",
    creator: "Srikalahasti Praja Seva Intelligence Platform",
    license: "Platform Proprietary Brand Emblem",
    attribution: "Srikalahasti Praja Seva Intelligence Platform Design System",
    permissionStatus: "Authorized Official Platform Brand Emblem",
    downloadedDate: "2026-08-07",
    requiresApproval: false,
    usagePurpose: "Primary Brand Logo for Public Header, Navigation, Footer & Favicon",
  },
  templeHero: {
    id: "templeHero",
    name: "Srikalahasteeswara Temple Gopuram Skyline",
    role: "Constituency Cultural Benchmark",
    imagePath: "/assets/portraits/temple-hero.svg",
    sourceUrl: "https://commons.wikimedia.org/wiki/Category:Srikalahasteeswara_Temple",
    creator: "Wikimedia Commons Contributors",
    license: "Creative Commons Attribution-ShareAlike (CC BY-SA 4.0)",
    attribution: "Wikimedia Commons Contributors / Cultural Heritage Archive",
    permissionStatus: "Verified Public Cultural Asset",
    downloadedDate: "2026-08-07",
    requiresApproval: false,
    usagePurpose: "Homepage Hero Graphic & Constituency Heritage Banner",
  },
};
