import Link from "next/link";
import { redirect } from "next/navigation";
import { getSession } from "@/lib/auth";
import { SAMPLE_COMPLAINTS } from "@/lib/db";
import { leadershipConfig } from "@/config/leadership";
import { geographyConfig } from "@/config/geography";

export const metadata = {
  title: "MLA Dashboard | Srikalahasti Praja Seva",
};

export default async function MLADashboardPage() {
  const session = await getSession();
  if (!session) redirect("/staff/login?redirect=/mla/dashboard");

  const rep = leadershipConfig.currentRepresentative;
  const complaints = SAMPLE_COMPLAINTS;
  const totalCases = complaints.length;
  const highPriority = complaints.filter(c => c.aiAnalysis?.urgency === "High" || c.aiAnalysis?.urgency === "Emergency").length;
  const underReview = complaints.filter(c => c.status === "Under Review").length;
  const resolved = complaints.filter(c => c.status === "Resolved" || c.status === "Closed").length;

  const card = {
    background: "rgba(13,33,55,0.6)",
    border: "1px solid rgba(212,160,23,0.12)",
    borderRadius: "16px",
    padding: "1.5rem",
  } as const;

  return (
    <main style={{ minHeight: "100vh", background: "#060f1a", color: "#f0f4f8" }}>
      {/* HEADER */}
      <header style={{ background: "rgba(13,33,55,0.95)", borderBottom: "1px solid rgba(212,160,23,0.15)", backdropFilter: "blur(20px)", position: "sticky", top: 0, zIndex: 50 }}>
        <div style={{ maxWidth: "1280px", margin: "0 auto", padding: "0 1.5rem", display: "flex", justifyContent: "space-between", alignItems: "center", height: "64px" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "1rem" }}>
            <Link href="/" style={{ color: "#64748b", textDecoration: "none", fontSize: "0.85rem" }}>← Home</Link>
            <div style={{ width: "1px", height: "20px", background: "rgba(255,255,255,0.1)" }} />
            <div>
              <div style={{ fontWeight: 700, color: "#D4A017", fontSize: "0.95rem" }}>Constituency Command Centre</div>
              <div style={{ fontSize: "0.65rem", color: "#64748b" }}>Srikalahasti No. {geographyConfig.constituency.number} · {session.role.replace("_", " ").toUpperCase()}</div>
            </div>
          </div>
          <div style={{ display: "flex", gap: "1rem", alignItems: "center" }}>
            <div style={{ padding: "0.25rem 0.75rem", background: "rgba(234,179,8,0.15)", border: "1px solid rgba(234,179,8,0.3)", borderRadius: "9999px", fontSize: "0.65rem", fontWeight: 700, color: "#eab308", letterSpacing: "0.1em" }}>
              SAMPLE PRESENTATION RECORDS
            </div>
            <form action="/api/auth/logout" method="POST">
              <button type="submit" style={{ padding: "0.4rem 0.875rem", border: "1px solid rgba(255,255,255,0.1)", borderRadius: "8px", background: "transparent", color: "#94a3b8", fontSize: "0.8rem", cursor: "pointer" }}>Sign Out</button>
            </form>
          </div>
        </div>
      </header>

      {/* WELCOME BANNER */}
      <div style={{ background: "linear-gradient(135deg, #0D2137 0%, #162f4a 100%)", borderBottom: "1px solid rgba(212,160,23,0.1)", padding: "1.5rem" }}>
        <div style={{ maxWidth: "1280px", margin: "0 auto", display: "flex", alignItems: "center", gap: "1.5rem" }}>
          <div style={{ width: "56px", height: "56px", borderRadius: "50%", border: "2px solid rgba(212,160,23,0.5)", display: "flex", alignItems: "center", justifyContent: "center", background: "#081424", fontSize: "1.5rem", flexShrink: 0 }}>👤</div>
          <div>
            <div style={{ fontWeight: 800, color: "#ffffff", fontSize: "1.25rem" }}>Welcome, {rep.name}</div>
            <div style={{ color: "#D4A017", fontSize: "0.85rem" }}>{rep.title}</div>
          </div>
          <div style={{ marginLeft: "auto", fontSize: "0.75rem", color: "#475569" }}>
            {new Date().toLocaleDateString("en-IN", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}
          </div>
        </div>
      </div>

      {/* AI DISCLAIMER */}
      <div style={{ maxWidth: "1280px", margin: "1.5rem auto", padding: "0 1.5rem" }}>
        <div style={{ background: "rgba(30,136,229,0.08)", border: "1px solid rgba(30,136,229,0.25)", borderRadius: "12px", padding: "1rem 1.25rem", display: "flex", gap: "0.75rem", alignItems: "flex-start" }}>
          <span style={{ flexShrink: 0, marginTop: "2px" }}>ℹ️</span>
          <div style={{ fontSize: "0.85rem", color: "#94a3b8", lineHeight: 1.6 }}>
            <strong style={{ color: "#60a5fa", display: "block", marginBottom: "2px" }}>AI-Generated Preliminary Assessments</strong>
            The insights below are generated by an LLM. This is not a finding of fact, a legal conclusion, or a determination of guilt. It is a prioritization tool to assist human review only. All cases require qualified human judgment before any action is taken.
          </div>
        </div>
      </div>

      <div style={{ maxWidth: "1280px", margin: "0 auto", padding: "0 1.5rem 3rem", display: "grid", gridTemplateColumns: "320px 1fr", gap: "2rem" }}>

        {/* LEFT COLUMN */}
        <div style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>

          {/* STATS */}
          <div style={{ ...card }}>
            <div style={{ fontWeight: 700, color: "#ffffff", marginBottom: "1rem" }}>Live Overview</div>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0.75rem" }}>
              {[
                { n: totalCases, label: "Total Cases", color: "#D4A017" },
                { n: highPriority, label: "High Priority", color: "#ef4444" },
                { n: underReview, label: "Under Review", color: "#60a5fa" },
                { n: resolved, label: "Resolved", color: "#22c55e" },
              ].map(s => (
                <div key={s.label} style={{ background: "rgba(6,15,26,0.6)", border: "1px solid rgba(255,255,255,0.05)", borderRadius: "10px", padding: "1rem", textAlign: "center" }}>
                  <div style={{ fontSize: "2rem", fontWeight: 900, color: s.color }}>{s.n}</div>
                  <div style={{ fontSize: "0.7rem", color: "#64748b", marginTop: "4px" }}>{s.label}</div>
                </div>
              ))}
            </div>
          </div>

          {/* CONTEXT */}
          <div style={{ ...card }}>
            <div style={{ fontWeight: 700, color: "#ffffff", marginBottom: "1rem" }}>Constituency Context</div>
            {[
              ["Mandals", "4"],
              ["Population (2011)", geographyConfig.constituency.baselinePopulation.toLocaleString()],
              ["Est. Personnel", `${geographyConfig.workforceEstimate.min}–${geographyConfig.workforceEstimate.max}`],
              ["District", geographyConfig.constituency.district],
            ].map(([k, v]) => (
              <div key={k} style={{ display: "flex", justifyContent: "space-between", padding: "0.6rem 0", borderBottom: "1px solid rgba(255,255,255,0.04)", fontSize: "0.85rem" }}>
                <span style={{ color: "#64748b" }}>{k}</span>
                <span style={{ color: "#ffffff", fontWeight: 700 }}>{v}</span>
              </div>
            ))}
            <div style={{ marginTop: "0.75rem", fontSize: "0.7rem", color: "#475569", lineHeight: 1.5 }}>{geographyConfig.workforceEstimate.disclaimer}</div>
          </div>

          {/* DEPT HEATMAP */}
          <div style={{ ...card }}>
            <div style={{ fontWeight: 700, color: "#ffffff", marginBottom: "1rem" }}>Department Heatmap</div>
            {[
              { dept: "Revenue", count: 42, color: "#ef4444" },
              { dept: "Municipality", count: 34, color: "#f97316" },
              { dept: "Police", count: 21, color: "#eab308" },
              { dept: "Health", count: 18, color: "#60a5fa" },
              { dept: "Panchayat Raj", count: 14, color: "#22c55e" },
              { dept: "Electricity", count: 11, color: "#a78bfa" },
            ].map(d => (
              <div key={d.dept} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "0.5rem 0", borderBottom: "1px solid rgba(255,255,255,0.04)" }}>
                <span style={{ fontSize: "0.85rem", color: "#94a3b8" }}>{d.dept}</span>
                <span style={{ padding: "0.2rem 0.6rem", borderRadius: "6px", background: `${d.color}22`, color: d.color, fontSize: "0.75rem", fontWeight: 700 }}>{d.count}</span>
              </div>
            ))}
          </div>

          <Link href="/" style={{ textAlign: "center", color: "#64748b", fontSize: "0.8rem", textDecoration: "none" }}>← Back to Public Site</Link>
        </div>

        {/* RIGHT COLUMN */}
        <div style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>
          <div style={{ fontWeight: 800, color: "#ffffff", fontSize: "1.25rem" }}>Recent AI Case Intelligence</div>

          {complaints.map(c => (
            <div key={c.id} style={{ background: "rgba(13,33,55,0.5)", border: "1px solid rgba(212,160,23,0.12)", borderRadius: "16px", overflow: "hidden" }}>
              {/* SAMPLE badge */}
              <div style={{ background: "rgba(234,179,8,0.08)", borderBottom: "1px solid rgba(234,179,8,0.12)", padding: "0.4rem 1rem", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                <span style={{ fontSize: "0.6rem", fontWeight: 700, color: "#eab308", letterSpacing: "0.12em", textTransform: "uppercase" }}>SAMPLE PRESENTATION RECORD</span>
                <span style={{ fontSize: "0.7rem", color: "#64748b" }}>{c.createdAt.split("T")[0]}</span>
              </div>

              <div style={{ padding: "1.25rem" }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "0.75rem" }}>
                  <h3 style={{ fontWeight: 700, color: "#ffffff", fontSize: "1rem", lineHeight: 1.4, maxWidth: "70%" }}>{c.aiAnalysis?.title ?? c.description.slice(0, 80)}</h3>
                  <span style={{ padding: "0.25rem 0.75rem", borderRadius: "9999px", background: c.status === "Under Review" ? "rgba(96,165,250,0.12)" : "rgba(34,197,94,0.12)", color: c.status === "Under Review" ? "#60a5fa" : "#22c55e", fontSize: "0.7rem", fontWeight: 700, whiteSpace: "nowrap" }}>{c.status}</span>
                </div>

                <div style={{ display: "flex", gap: "0.5rem", marginBottom: "1rem", flexWrap: "wrap" }}>
                  <span style={{ padding: "0.2rem 0.6rem", background: "rgba(255,255,255,0.05)", borderRadius: "6px", fontSize: "0.72rem", color: "#94a3b8" }}>{c.id}</span>
                  <span style={{ padding: "0.2rem 0.6rem", background: "rgba(255,255,255,0.05)", borderRadius: "6px", fontSize: "0.72rem", color: "#94a3b8" }}>{c.department ?? c.aiAnalysis?.department}</span>
                  <span style={{ padding: "0.2rem 0.6rem", background: "rgba(255,255,255,0.05)", borderRadius: "6px", fontSize: "0.72rem", color: "#94a3b8" }}>{c.mandal} Mandal</span>
                </div>

                <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "0.75rem", background: "rgba(6,15,26,0.5)", borderRadius: "10px", padding: "1rem", border: "1px solid rgba(255,255,255,0.05)" }}>
                  <div>
                    <div style={{ fontSize: "0.6rem", color: "#475569", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: "4px" }}>AI Credibility</div>
                    <div style={{ fontWeight: 700, fontSize: "0.9rem", color: c.aiAnalysis?.credibilityBand === "High" ? "#22c55e" : c.aiAnalysis?.credibilityBand === "Medium" ? "#eab308" : "#ef4444" }}>
                      {c.aiAnalysis?.credibilityBand} ({c.aiAnalysis?.confidenceScore}%)
                    </div>
                  </div>
                  <div>
                    <div style={{ fontSize: "0.6rem", color: "#475569", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: "4px" }}>Urgency</div>
                    <div style={{ fontWeight: 700, fontSize: "0.9rem", color: c.aiAnalysis?.urgency === "High" || c.aiAnalysis?.urgency === "Emergency" ? "#ef4444" : "#f97316" }}>
                      {c.aiAnalysis?.urgency}
                    </div>
                  </div>
                  <div style={{ display: "flex", alignItems: "center", justifyContent: "flex-end" }}>
                    <Link href={`/mla/complaint/${c.id}`} style={{ padding: "0.5rem 1rem", border: "1px solid #D4A017", borderRadius: "8px", color: "#D4A017", textDecoration: "none", fontSize: "0.8rem", fontWeight: 700 }}>
                      Review Case →
                    </Link>
                  </div>
                </div>

                <div style={{ marginTop: "0.75rem", fontSize: "0.72rem", color: "#475569", lineHeight: 1.5 }}>
                  {c.aiAnalysis?.legalDisclaimer}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}
